config/routes.rb
Rails.application.routes.draw do
root :to => 'home#index'

get 'home/about', to: 'home#about'


devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books, :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true

	validates :body, length: { maximum: 200 },
			presence: true

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attachment :profile_image

  validates :introduction, length: { maximum: 50 }

  validates :name, length: { minimum: 2, maximum: 20 },
  			presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end


  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	  before_action :authenticate_user!
	  before_action :correct_user, only: [:edit, :destroy]
	
	def index
	    @book = Book.new
	    @books = Book.all
	    @user = User.find(current_user.id)
	end


	def show
	    @book = Book.find(params[:id])
	    @new_book = Book.new
	    @user = @book.user 
	end


	def edit
	    @book = Book.find(params[:id])
	end

	def new
	end


	def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
    	@books = Book.all
    	@user = current_user
        if @book.save
		  # 作成に成功した場合、 /books/{book_id} にリダイレクト
		   redirect_to book_path(@book.id)
           flash[:notice] = "successfully"
		else
           render :index
           # infrc.html.erb
		  # 作成に失敗した場合、 /books/edit に戻してバリデーションエラーを表示する
		  # view 側で、 @book.errors を使ってエラーを表示する。
		end
	end


	def update
	    @book = Book.find(params[:id])
	    if
	      @book.update(book_params)
      	  redirect_to book_path(@book.id)
      	  flash[:notice] = "successfully"
    	else
    	  render :edit
    	end
	end


	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end
	

    private

    def correct_user
    	if current_user != Book.find(params[:id]).user
    		redirect_to books_path
    	end
    end

    def book_params
        params.require(:book).permit(:title,:body)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

	def index
      @book = Book.new
      @user = current_user
      @users = User.all
	end

	def new
	end


	def show
	  @user = User.find(params[:id])
	  @book = Book.new
	  @books = @user.books
	end


	def edit
	  if params[:id] == current_user.id
	    @user = User.find(params[:id])
	    render action: :edit
	  else
	    @user = current_user
	  end
	end
	
	def update
	  @user = User.find(params[:id])
	  if
	    @user.update(user_params)
	    flash[:notice] = "successfully."
	    redirect_to user_path(@user.id)
	  else
	    render :edit
	  end
	end


	private
	  def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	  end

	  def correct_user
        @user = User.find(params[:id])
        redirect_to(user_url(current_user)) unless @user == current_user
	  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Editing Book</h1>

    <%= render 'layouts/error_messages', model: @book %>
	<%= form_for(@book, url: book_path(@book), method: :patch) do |f| %>
	  <p>Title</p>
	  <%= f.text_field :title %>
	  <p>Opinion</p>
	  <%= f.text_area :body %>
	  <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
	<% end %>

	<%= link_to "Show", book_path %>
	|
	<%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
    <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb", size:'100x100' %>
        <table class="table">
          <tr>
　　        <th>name</th>
　　        <th><%= @user.name %></th>
　        </tr>
　        <tr>
　　        <th>introduction</th>
　　        <th><%= @user.introduction %></th>
　　      </tr>
        </table>
      <%= link_to  edit_user_path(current_user), class: "btn btn-default col-xs-12" do %>
        <i class="fa fa-wrench"></i>
      <% end %>
      <h2> New book</h2>
      <%= render 'layouts/error_messages', model: @book %>
      <%= form_for(@book, url: '/users') do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "col-xs-12" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "col-xs-12" %>
        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        <% end %>
    </div>


    <div class="col-xs-9">
    	<h2>Books</h2>
    	<table class="table table-hover table-inverse">
    	  <thead>
    	    <tr>
    	      <th></th>
    	      <th>Title</th>
    	      <th>Opinion</th>
    	      <th colspan="3"></th>
    	    </tr>
    	  </thead>

        <% @books.each do |book| %>
    	  <tbody>
      	  <tr>
      	  	<td>
              <%= link_to(user_path(book.user)) do %>
      	  	  <%= attachment_image_tag book.user, :profile_image, :fill, 250, 250, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
      	  	</td>
      	  	<td><%= link_to book.title, book_path(book) %></td>
      	  	<td><%= book.body %></td>
      	  </tr>
    	  </tbody>
        <% end %>
    	</table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
    <p>User info</p>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb", size:'100x100' %>
        <table class="table">
          <tr>
　　        <th>name</th>
　　        <th><%= @user.name %></th>
　        </tr>
　        <tr>
　　        <th>introduction</th>
　　        <th><%= @user.introduction %></th>
　　      </tr>
        </table>
      <%= link_to  edit_user_path, class: "btn btn-default" do %>
        <i class="fa fa-wrench"></i>
      <% end %>
      <p>New book</p>
      <%= form_for @new_book do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "col-xs-12" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "col-xs-12" %>
        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        <% end %>
    </div>
  

    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to(user_path(@user)) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
        <% if @book.user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book), class: "btn-sm btn-danger", method: :delete %>
            </td>
        <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="body">
  <div class="container">
  	<p id="notice"></p>
  	<h1>
  	Welcome to 
  	  <span class="glyphicon glyphicon-book"></span>
  	<strong>Bookers</strong>
  	!
    </h1>
  </div>
</div>

app/views/home/index.html.erb
<div class="body">
  <div class="container">
  	<p id="notice"></p>
  	<div class="row">
  	  <div class="top-message col-md-offset-3 col-md-6">
  	  	<h1>
  	  	  welcome to 
  	  	  <span class="glyphicon glyphicon-book"></span>
  	  	  <strong>Bookers</strong>
  	  	  	  !!
  	  	</h1>
  	  	<p>
  	  	  In  
  	  	  <span class="glyphicon glyphicon-book"></span>
  	  	  <strong>Bookers</strong>
  	  	  , 
  	  	</p>
  	  	<p>you can share and exchange  your opinions , inpressions , and emotions</p>
  	  	<p> about various books!</p>
  	  	<div class="btn-wrapper">
  	  	  <div class="row">
  	  	  	<p>
  	  	  	  <a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a>
  	  	  	</p>
  	  	  </div>
  	  	  <div class="row">
  	  	  	<p>
  	  	  	  <a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a>
  	  	  	</p>
  	  	  </div>
  	  	</div>
  	  </div>
  	</div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
    	<li><%= model.errors.count %>errors </li>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>
      <nav class="navbar navbar-main navbar-shadow navbar-inverse" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <h1 class="navbar-logo" href="/">
              <strong id="white">Bookers</strong>
            </h1>
   
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right">
  	      	  <% if user_signed_in? %>
              	<li>
                  <%= link_to user_path(current_user) do %>
                    <span class="glyphicon glyphicon-home home">Home<span>
                  <% end %>
                </li>

                <li>
                  <%= link_to "/users" do %>
                    <span class="glyphicon glyphicon-user users">Users<span>
                  <% end %>
                </li>

                <li>
                  <%= link_to books_path do %>
                    <span class="glyphicon glyphicon-book books">Books<span>
                  <% end %>
                </li>

                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete">logout<span>
                  <% end %>
                </li>

              <% else %>
                <li>

                <li>
                  <%=  link_to root_path do %>
                    <span class="glyphicon glyphicon-home home">Home<span>
                  <% end %>
                </li>

                <li>
                  <%=  link_to home_about_path do %>
                    <span class="glyphicon glyphicon-link about">About<span>
                  <% end %>
                </li>

                <li>
                  <%=  link_to "/users/sign_up" do %>
                    <span class="glyphicon glyphicon-link about">sign up<span>
                  <% end %>
                </li>

                <li>
                  <%=  link_to "/users/sign_in" do %>
                    <span class="glyphicon glyphicon-log-in sign_in">login<span>
                  <% end %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
    <%= yield %>


    <footer class="">
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <p id="notice"></p>
      <%= render 'layouts/error_messages', model: @user %>
  <h2>User info</h2>
	<div class="field">
	  <%= form_for(@user, url:"/users/#{@user.id}") do |f| %>
	  <a>Name</a><br>
	  <%= f.text_area :name %><br>
	  <a>Image</a><br>
	  <%= f.file_field :profile_image %><br>
	  <a>Introduction<br>
	  <%= f.text_area :introduction %><br><br>
	  <%= f.submit 'Update User' %></a>
	  <% end %><br>
  </form>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
	  <div class="col-xs-3">
	    <h2>User info</h2>
	      <%= attachment_image_tag @user, :profile_image, :fill, 250, 250, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
	      <table class="table">
	        <tr>
	          <th>name</th>
	          <th><%= @user.name %></th>
	　      </tr>
	　      <tr>
	　　       <th>introduction</th>
	　　       <th><%= @user.introduction %></th>
			</tr>
	      </table>

	    <%= link_to edit_user_path(@user), class: "col-xs-12 btn btn-default" do %>
	      <i class="fa fa-wrench"></i>
	    <% end %>
	    <h2> New book</h2>
	    <%= form_for(@book, url: '/users') do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "col-xs-12" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "col-xs-12" %>
        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        <% end %>
	  </div>
	


    <div class="col-xs-9">
    	<h2>Users</h2>
    	<table class="table table-hover table-inverse">
    	  <thead>
    	    <tr>
    	      <th>Image</th>
    	      <th>Name</th>
    	      <th></th>
    	      <th colspan="3"></th>
    	    </tr>
    	  </thead>
        <% @users.each do |user| %>
    	  <tbody>
      	  <tr>
      	  	<td>
      	  	  <%= attachment_image_tag user, :profile_image, :fill, 250, 250, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
      	  	</td>
      	  	<td><%= user.name %></td>
      	  	<td><%= link_to "Show", user_path(user) %></td>
      	  </tr>
    	  </tbody>
        <% end %>
    	</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
    <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb", size:'100x100' %>
        <table class="table">
          <tr>
　　        <th>name</th>
　　        <th><%= @user.name %></th>
　        </tr>
　        <tr>
　　        <th>introduction</th>
　　        <th><%= @user.introduction %></th>
　　      </tr>
        </table>
      <%= link_to  edit_user_path, class: "btn btn-default col-xs-12" do %>
        <i class="fa fa-wrench"></i>
      <% end %>
      <p>New book</p>
      <%= form_for @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "col-xs-12" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "col-xs-12" %>
        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        <% end %>
    </div>

    <div class="col-xs-9">
      <p>Book detail</p>
      <table class="table table-hover">
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image %><br>
              <%= book.user.name %>
            </td>
            <td><%=link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= link_to "Edit", edit_book_path(book.id), class: "btn btn-success" %></td>
            <td><%= link_to "Delete", book_path(book.id), class: "btn btn-danger", method: :delete %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>